# Form implementation generated from reading ui file 'AddLink.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_AddLink(object):
    def setupUi(self, Form_AddLink):
        Form_AddLink.setObjectName("Form_AddLink")
        Form_AddLink.resize(749, 421)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/subway--add.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_AddLink.setWindowIcon(icon)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Form_AddLink)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=Form_AddLink)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit_ListLink = QtWidgets.QTextEdit(parent=self.groupBox)
        self.textEdit_ListLink.setObjectName("textEdit_ListLink")
        self.horizontalLayout.addWidget(self.textEdit_ListLink)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(558, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_OK = QtWidgets.QPushButton(parent=Form_AddLink)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.horizontalLayout_2.addWidget(self.pushButton_OK)
        self.pushButton_Cancel = QtWidgets.QPushButton(parent=Form_AddLink)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_Cancel)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)

        self.retranslateUi(Form_AddLink)
        QtCore.QMetaObject.connectSlotsByName(Form_AddLink)

    def retranslateUi(self, Form_AddLink):
        _translate = QtCore.QCoreApplication.translate
        Form_AddLink.setWindowTitle(_translate("Form_AddLink", "Add link"))
        self.groupBox.setTitle(_translate("Form_AddLink", "Paste Google Drive Link ( One per line ):"))
        self.pushButton_OK.setText(_translate("Form_AddLink", "OK"))
        self.pushButton_Cancel.setText(_translate("Form_AddLink", "Cancel"))
